name: Generate Tokens On Input

on:
    push:
        paths:
            - 'input/tokens.json'

jobs:
    generate_tokens:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm ci, build
              run: |
                  npm ci
                  npm run build
            - name: Commit Generated Platform Deliverables
              id: 'auto-commit-action'
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update platform deliverables
